APP_INITIAL_TICKERS = ["QQQ", "SPY", "VTI", "VT"]
APP_DATE_START = "2000-01-01"
APP_INITIAL_INTERVAL_DAYS = 365

PRICES_RETRIEVAL_INTERVAL = "1d"
PRICES_EPS = 1e-6
PRICES_ROLLING_WINDOW = 251
PRICES_ROLLING_MIN_PERIOD = 1
